### ISSUE TITLE
does your vim setup indent one-line conditionals correctly?

### ISSUE THREAD

**Issue by dankelley** [hongyuanjia/dotfiles#1]
Hi Hongyuan Jia.  Late last year, you were kind enough to suggest a `.config/nvim/init.lua` file to me (in comment https://github.com/jalvesaq/Nvim-R/issues/708).  I wonder, if you edit the following and try to indent it, does the second line indent?  It doesn't for me, when I use your `init.lua` file (downloaded a few minutes ago).

```R
if (TRUE)
message("should be indented")
```

Please ignore this comment, if you are busy.  I just thought I would reach out because my understanding of lsp/treesitter/etc is still quite weak and I've been unable to find what part of `init.lua` might relate to this issue.

Dan.

**Comment by hongyuanjia** [comment]
Hi @dankelley, sorry for the late reply. Yes, you are right, the second line did not indent. This is a limitation of the treesitter. For R, I think Nvim-R implements a more comprehensive indentation algorithm. You can disable treesitter indent feature by setting `indent = { disable = { "r"} }` like below:

```lua
            require("nvim-treesitter.configs").setup({
				...
                indent = { enable = true, disable = { "r" } },
				...
			})
```

**Comment by dankelley** [comment]
@hongyuanjia thanks *very* much for the reply.  This works perfectly!!  I am very appreciative.  Dan.
